name: lxd
version: 0.0.6

description:
  Provides a client to access lxd, which allows you to manage containers on a Linux system.

homepage: https://github.com/canonical/lxd.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  linux:

dependencies:
  collection: ^1.15.0
  http: ^0.13.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
  test_cov: ^1.0.1

