name: lxd
version: 0.0.3

description:
  Provides a client to access lxd, which allows you to manage containers on a Linux system.

homepage: https://github.com/canonical/lxd.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
